module.exports = {
    EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY,
    EXPO_PUBLIC_AZURE_URL: process.env.EXPO_PUBLIC_AZURE_URL,
    EXPO_PUBLIC_REVENUECAT_PROJECT_GOOGLE_API_KEY: process.env.EXPO_PUBLIC_REVENUECAT_PROJECT_GOOGLE_API_KEY,
    EXPO_PUBLIC_CONVEX_URL: process.env.EXPO_PUBLIC_CONVEX_URL
  };

